// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSWpPUVhHFbVyJwxrLADoBnJAcodNn6PM',
    appId: '1:93818868367:web:e3f996cbcadd5061f956fa',
    messagingSenderId: '93818868367',
    projectId: 'flutter-firebase-7b402',
    authDomain: 'flutter-firebase-7b402.firebaseapp.com',
    storageBucket: 'flutter-firebase-7b402.firebasestorage.app',
    measurementId: 'G-YFS3BNZ3W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-2gFl4S811NTE03Qesd4ocNzAtjYU5t4',
    appId: '1:93818868367:android:895545c4e1b7f8f6f956fa',
    messagingSenderId: '93818868367',
    projectId: 'flutter-firebase-7b402',
    storageBucket: 'flutter-firebase-7b402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXYgksCAYM0ZialSfQw8YTlFt3jSOjCpo',
    appId: '1:93818868367:ios:d7942ec1bc1176abf956fa',
    messagingSenderId: '93818868367',
    projectId: 'flutter-firebase-7b402',
    storageBucket: 'flutter-firebase-7b402.firebasestorage.app',
    iosClientId: '93818868367-rdg1k691hrphfrdhg8r7mucc3piod7l1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXYgksCAYM0ZialSfQw8YTlFt3jSOjCpo',
    appId: '1:93818868367:ios:d7942ec1bc1176abf956fa',
    messagingSenderId: '93818868367',
    projectId: 'flutter-firebase-7b402',
    storageBucket: 'flutter-firebase-7b402.firebasestorage.app',
    iosClientId: '93818868367-rdg1k691hrphfrdhg8r7mucc3piod7l1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSWpPUVhHFbVyJwxrLADoBnJAcodNn6PM',
    appId: '1:93818868367:web:5636464b6b05d6cef956fa',
    messagingSenderId: '93818868367',
    projectId: 'flutter-firebase-7b402',
    authDomain: 'flutter-firebase-7b402.firebaseapp.com',
    storageBucket: 'flutter-firebase-7b402.firebasestorage.app',
    measurementId: 'G-VR37GH9VG4',
  );
}
